spring:
  datasource:
    url: jdbc:mysql://localhost:3306/person_registry?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: registry
    password: registry
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
